parameters:
#    c_duc_page.example.class: CDuc\PageBundle\Example

services:
#    c_duc_page.example:
#        class: %c_duc_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
