parameters:
#    c_duc_campagne.example.class: CDuc\CampagneBundle\Example

services:
#    c_duc_campagne.example:
#        class: %c_duc_campagne.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
