parameters:
#    c_duc_charracter.example.class: CDuc\CharracterBundle\Example

services:
#    c_duc_charracter.example:
#        class: %c_duc_charracter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
