parameters:
#    c_duc_main.example.class: CDuc\MainBundle\Example

services:
#    c_duc_main.example:
#        class: %c_duc_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
